/**
 * Pure authorization helpers — no Next.js or framework imports.
 * Safe to unit-test in Node without a Next runtime.
 */

import {
  PARTNER_ROLES,
  PERMISSIONS,
  PLATFORM_ROLES,
  type PartnerRole,
  type Permission,
  type PlatformRole,
  isPartnerRoleValue,
  isPlatformRoleValue,
} from "./roles";

const ALL_PLATFORM_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.MANAGE_PLATFORM,
  PERMISSIONS.MANAGE_USERS,
  PERMISSIONS.MANAGE_ORGANIZATIONS,
  PERMISSIONS.APPROVE_PARTNERS,
  PERMISSIONS.APPROVE_RENTERS,
  PERMISSIONS.APPROVE_VEHICLES,
  PERMISSIONS.MANAGE_VEHICLES,
  PERMISSIONS.MANAGE_RESERVATIONS,
  PERMISSIONS.MANAGE_PAYMENTS,
  PERMISSIONS.MANAGE_PAYOUTS,
  PERMISSIONS.VIEW_LEDGER,
  PERMISSIONS.MANAGE_FEE_AGREEMENTS,
  PERMISSIONS.MANAGE_MAINTENANCE,
  PERMISSIONS.MANAGE_SUPPORT,
  PERMISSIONS.VIEW_AUDIT_LOGS,
  PERMISSIONS.MANAGE_NOTIFICATIONS,
  PERMISSIONS.VIEW_REPORTS,
];

const ALL_PARTNER_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.PARTNER_MANAGE_ORG,
  PERMISSIONS.PARTNER_MANAGE_TEAM,
  PERMISSIONS.PARTNER_MANAGE_VEHICLES,
  PERMISSIONS.PARTNER_VIEW_VEHICLES,
  PERMISSIONS.PARTNER_MANAGE_AVAILABILITY,
  PERMISSIONS.PARTNER_VIEW_RESERVATIONS,
  PERMISSIONS.PARTNER_VIEW_PAYOUTS,
  PERMISSIONS.PARTNER_VIEW_STATEMENTS,
  PERMISSIONS.PARTNER_MANAGE_DOCUMENTS,
  PERMISSIONS.PARTNER_VIEW_REPORTS,
];

export const ROLE_PERMISSIONS: Record<PlatformRole, readonly Permission[]> = {
  [PLATFORM_ROLES.SUPER_ADMIN]: ALL_PLATFORM_PERMISSIONS,
  [PLATFORM_ROLES.PERMANENCE_ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ORGANIZATIONS,
    PERMISSIONS.APPROVE_PARTNERS,
    PERMISSIONS.APPROVE_RENTERS,
    PERMISSIONS.APPROVE_VEHICLES,
    PERMISSIONS.MANAGE_VEHICLES,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.MANAGE_PAYOUTS,
    PERMISSIONS.VIEW_LEDGER,
    PERMISSIONS.MANAGE_FEE_AGREEMENTS,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.MANAGE_SUPPORT,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [PLATFORM_ROLES.OPERATIONS_MANAGER]: [
    PERMISSIONS.APPROVE_PARTNERS,
    PERMISSIONS.APPROVE_RENTERS,
    PERMISSIONS.APPROVE_VEHICLES,
    PERMISSIONS.MANAGE_VEHICLES,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.MANAGE_SUPPORT,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [PLATFORM_ROLES.FINANCE_MANAGER]: [
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.MANAGE_PAYOUTS,
    PERMISSIONS.VIEW_LEDGER,
    PERMISSIONS.MANAGE_FEE_AGREEMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  [PLATFORM_ROLES.RENTAL_AGENT]: [
    PERMISSIONS.APPROVE_RENTERS,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.MANAGE_SUPPORT,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [PLATFORM_ROLES.MAINTENANCE_COORDINATOR]: [
    PERMISSIONS.MANAGE_VEHICLES,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [PLATFORM_ROLES.SUPPORT_AGENT]: [
    PERMISSIONS.MANAGE_SUPPORT,
    PERMISSIONS.VIEW_REPORTS,
  ],
};

export const PARTNER_ROLE_PERMISSIONS: Record<
  PartnerRole,
  readonly Permission[]
> = {
  [PARTNER_ROLES.PARTNER_OWNER]: ALL_PARTNER_PERMISSIONS,
  [PARTNER_ROLES.PARTNER_MANAGER]: [
    PERMISSIONS.PARTNER_MANAGE_TEAM,
    PERMISSIONS.PARTNER_MANAGE_VEHICLES,
    PERMISSIONS.PARTNER_VIEW_VEHICLES,
    PERMISSIONS.PARTNER_MANAGE_AVAILABILITY,
    PERMISSIONS.PARTNER_VIEW_RESERVATIONS,
    PERMISSIONS.PARTNER_VIEW_PAYOUTS,
    PERMISSIONS.PARTNER_VIEW_STATEMENTS,
    PERMISSIONS.PARTNER_MANAGE_DOCUMENTS,
    PERMISSIONS.PARTNER_VIEW_REPORTS,
  ],
  [PARTNER_ROLES.PARTNER_STAFF]: [
    PERMISSIONS.PARTNER_VIEW_VEHICLES,
    PERMISSIONS.PARTNER_MANAGE_AVAILABILITY,
    PERMISSIONS.PARTNER_VIEW_RESERVATIONS,
    PERMISSIONS.PARTNER_MANAGE_DOCUMENTS,
  ],
  [PARTNER_ROLES.PARTNER_ACCOUNTANT]: [
    PERMISSIONS.PARTNER_VIEW_VEHICLES,
    PERMISSIONS.PARTNER_VIEW_RESERVATIONS,
    PERMISSIONS.PARTNER_VIEW_PAYOUTS,
    PERMISSIONS.PARTNER_VIEW_STATEMENTS,
    PERMISSIONS.PARTNER_VIEW_REPORTS,
  ],
  [PARTNER_ROLES.PARTNER_READ_ONLY]: [
    PERMISSIONS.PARTNER_VIEW_VEHICLES,
    PERMISSIONS.PARTNER_VIEW_RESERVATIONS,
    PERMISSIONS.PARTNER_VIEW_PAYOUTS,
    PERMISSIONS.PARTNER_VIEW_STATEMENTS,
    PERMISSIONS.PARTNER_VIEW_REPORTS,
  ],
};

export function isPlatformRole(
  role: string | null | undefined,
): role is PlatformRole {
  return typeof role === "string" && isPlatformRoleValue(role);
}

export function isPartnerRole(
  role: string | null | undefined,
): role is PartnerRole {
  return typeof role === "string" && isPartnerRoleValue(role);
}

export function can(
  role: PlatformRole | string | null | undefined,
  permission: Permission,
): boolean {
  if (!isPlatformRole(role)) return false;
  return ROLE_PERMISSIONS[role].includes(permission);
}

export function partnerCan(
  partnerRole: PartnerRole | string | null | undefined,
  permission: Permission,
): boolean {
  if (!isPartnerRole(partnerRole)) return false;
  return PARTNER_ROLE_PERMISSIONS[partnerRole].includes(permission);
}

export function permissionsFor(
  role: PlatformRole | PartnerRole | string | null | undefined,
): readonly Permission[] {
  if (isPlatformRole(role)) return ROLE_PERMISSIONS[role];
  if (isPartnerRole(role)) return PARTNER_ROLE_PERMISSIONS[role];
  return [];
}
